### PR TITLE
Numerous Bug Fixes

### PR DESCRIPTION
**Pull request by microalps**
Added unit tests to demonstrate the bugs I encountered with this library (and the original fork). Method signatures had to change unfortunately to fix the no sunrise bug.

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks for your contribution! I've had a look through the code and if I just run the TestConsole in both your updated code and in my code, the output of my code actually more closely resembles what most sites on the internet are displaying for my location. 

Also when I run the Unit Tests you have added in your code, they don't all pass. Is this intentional?

image

**Comment by microalps** [comment]
See my original commit message that NOOA revised their formula. Most libraries are using the old formula. To get seconds, I used Chrome to open https://www.esrl.noaa.gov/gmd/grad/solcalc/ and opened the Developer Console.
image
1. Click Sources
2. Browse to main.js
3. Change this line to ,3 instead of ,2 for seconds to be included. There are other places too, but for this use case this is the only change.
4. Ctrl+S to save (temporarily)
5. Change date or time on the web page to see seconds now!

FYI - you will also see in this screenshot the same change I applied -- var newTimeUTC on Line 549 is the same addition my code implemented
image

**Comment by microalps** [comment]
Added revised tests to make the test suite pass in timezones other than EST. Applied same patch to failing-tests branch (microalps/SunSetRiseLib@bde21a94ec3f6face1ae612f76d67123159ebfa0) so you can see them failing using same unit test prior to the changes.

**Comment by KoenZomers** [comment]
Excellent! Thanks for the very clear steps. I made a small modification to also allow for timezones lying between timezones, i.e. Darwin at UTC+9.5. Also seems to work well now with your code update.

Much appreciated contribution, thanks!

**Pull request merged**
